### PR TITLE
Added functionality for delayed reloading of pages upon key press.

### PR DESCRIPTION
**Pull request by ghost**
With the variable impatient-mode-delayed-update set to 1 reloading
of buffers in the browser is delayed until there is 1 second of
inactivity in that buffer.  This is so that if you are typing in
a style rule or html tag broken code is not loaded into the browser.

### CODE REVIEW

**Comment by netguy204** [comment]
Thanks for the contribution!

**Comment by skeeto** [comment]
I have some feedback:

In Emacs Lisp, 0 and 1 are not used for true and false. Both are true values. The 1 suggests it has some meaning other than true, which is not the case.

Second, the timeout should be configurable. The Elisp way to do this is combine this option with the on/off option so that the whole delay is disabled when the timeout is set to nil, otherwise it uses that number of seconds (floats allowed). Maybe call it `impatient-mode-delay`?

Third, it would be much better to use a single, global idle timer (via `run-with-idle-timer`). The logic is pretty simple, and it's all about managing a timer on events:

When a key is pressed and delay is non-nil:

* If the timer hasn't been started yet, start the idle timer on repeat with the appropriate delay.
* If the timer has been started but its delay doesn't match the configured delay, fix it (`timer-set-idle-time`).
* Mark the buffer as changed.

In the timer function (run after Emacs has been idle):

* If the delay is nil, cancel the timer and send out the buffer. The delay was cleared since the last keystroke and this timer firing.
* If the delay doesn't match the timer's setting, update it (`timer-set-idle`). The delay was changed between the last keystroke and the idle timeout. If the delay is now longer, we wait a bit longer. If the delay is shorter, it will fire again immediately.
* Otherwise send changed buffers to clients. This is the most common case.

If a key is pressed and the delay is nil:

* If the timer exists, cancel it. The delay was disabled since the last keystroke. This is uncommon.
* And send changed buffers to clients.

Finally, this feature should be disabled by default.

**Comment by netguy204** [comment]
@Jeremiah-B I'm handing maintenance of this package over to @skeeto (should have done that years ago!) Please work with him to improve this change at https://github.com/skeeto/impatient-mode

**Comment by ghost** [comment]
I've implemented the changes @skeeto suggested and will create a PR at his copy of the repository.   Thanks for the pointers!  I'm not too familiar with emacs lisp and most of what I know is based on my knowledge of clojure.

**Pull request merged**
